apiVersion: batch/v1
kind: Job
metadata:
  name: user-crud-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: mazurenkoaa/user-crud:1.0
        command: ["alembic",  "upgrade", "head"]
        env:
          - name: pg_host
            valueFrom:
              configMapKeyRef:
                name: user-crud
                key: pg_host
          - name: pg_user
            valueFrom:
              configMapKeyRef:
                name: user-crud
                key: pg_user
          - name: pg_db
            valueFrom:
              configMapKeyRef:
                name: user-crud
                key: pg_db
          - name: pg_password
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: password
      restartPolicy: Never
  backoffLimit: 4